version: '3'

services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    networks:
      bannercircle:
        aliases: [ db ]
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 15s

  notify:
    image: apache/kafka:latest
    networks:
      bannercircle:
        aliases: [ notify ]
    ports:
      - 9092:9092

  migrations:
    image: service:dev
    command: /bin/sh -c "sleep 5 && /app/service migrate"
    networks:
      bannercircle:
        aliases: [ migrations ]
    depends_on:
      db:
        condition: service_healthy

  app:
    image: service:dev
    command: /bin/sh -c "sleep 15 && /app/service start"
    networks:
      bannercircle:
        aliases: [ app ]
    ports:
      - 8088:8088

networks:
  bannercircle:
