services:

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
    networks:
      - bannercircle
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 15s

  notify:
    image: bitnami/kafka:latest
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    networks:
      - bannercircle
    ports:
      - 9092:9092

  migrations:
    image: service:dev
    command: /bin/sh -c "sleep 10 && /app/service migrate"
    networks:
      - bannercircle
    depends_on:
      db:
        condition: service_healthy

  app:
    image: service:dev
    command: /bin/sh -c "sleep 25 && /app/service start"
    networks:
      - bannercircle
    ports:
      - 8088:8088
    restart: on-failure:1

networks:
  bannercircle:
    driver: bridge
