storage:
  host: db
  port: 5432
  dbname: app
  user: app
  password: app
notify:
  host: notify
  port: 9092
  topic: banner
  partition: 0
service:
  host: 0.0.0.0
  port: 8088
logger:
  level: debug