name: BannerCircle CI

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  
  tests:
  
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          install-mode: goinstall
          version: latest
      
      - name: Run tests
        run: go test -v -race -count 10 ./...
      
      - name: Build app
        run: go build -o bin/service main.go
